### ISSUE TITLE
Use PSR instead of Guzzle

### ISSUE THREAD

**Issue by garak** [mikemilano/xrphp#2]
It would be nice to not set an hard dependency on Guzzle.
You can require https://packagist.org/packages/php-http/ and then suggest an adapter.
Of course, you'll need to require-dev a concrete adapter (maybe just the Guzzle one, so you won't need to change too much) and use it in your tests.

**Comment by mikemilano** [comment]
How can I argue with a name like that! :D ... I wasn't aware of this. I'll look into implementing once I educate myself.

**Comment by mikemilano** [comment]
Great call. Now users can choose their own HTTP client & I can easily mock API responses in my tests.
