### ISSUE TITLE
Receive payments using destination tag

### ISSUE THREAD

**Issue by miranos** [mikemilano/xrphp#3]
Hi,

Any example on how to receive payment using destination tag please ?

Thank's

**Comment by mikemilano** [comment]
I am guessing you mean sending transactions with a destination tag?

First, I wouldn't recommend using the library right now. It's under heavy development and not very usable. I expect to have it ready to start testing within another week or 2.

That said, take a look at the [Transaction Documentation](https://github.com/foxrp/xrphp/blob/master/docs/Transactions.md) to get an idea of how it is going to work. Your answer will depend if you're signing locally or remotely. Given the example in the documentation, you would just need to add `DestinationTag` value to the transaction parameters.

**Comment by miranos** [comment]
Your example demontrate how we are able to make transaction from account to another one.

If i want receive payment to my account only ? using destination tag to identify the sender, is it possible using your library please ?

Or i have to set in Sender & Receiver same account (Wallet) ?

Thank you

**Comment by mikemilano** [comment]
Once a transaction is sent, it is validated/accepted by the XRP ledger. Once accepted, they are already in their final destination as far as the ledger is concerned.

Exchanges may have additional software that analyze transactions to their accounts, and move value to their customers based on the destination tags, but that is beyond the scope of this library.
