### ISSUE TITLE
API methods that don't require parameters throws an invalid argument warning

### ISSUE THREAD

**Issue by submtd** [mikemilano/xrphp#5]
API requests such as 'fee' and 'server_info' that do not take any parameters throw a warning

Invalid argument supplied for foreach() in .....foxrp/rippled-php/src/Api/AbstractFieldable.php on line 82

**Comment by mikemilano** [comment]
Thanks for the report.

You can now omit the `$params` argument for methods which do not require them.

```
$response = $client->send('server_info');
```
