### ISSUE TITLE
PHP 7.2 can not install from composer

### ISSUE THREAD

**Issue by congnghiakhiem** [mikemilano/xrphp#6]
```
>composer require foxrp/rippled-php


  [InvalidArgumentException]
  Could not find a version of package foxrp/rippled-php matching your minimum-stability (stable).
   Require it with an explicit version constraint allowing its desired stability.
```
I use PHP 7.2
```
>php -v
PHP 7.2.10 (cli) (built: Sep 13 2018 00:48:27) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by congnghiakhiem** [comment]
Same problem with PHP 7.1
```PHP 7.1.10 (cli) (built: Sep 26 2017 20:04:32) ( ZTS MSVC14 (Visual C++ 2015) x64 )```

**Comment by mikemilano** [comment]
Did you install the dependencies first?

```
composer require php-http/guzzle6-adapter php-http/message
composer require foxrp/rippled-php
```

Just tested this successfully on PHP 7.2.7. Before that however, I was able to reproduce your results by skipping the dependencies (`php-http/guzzle6-adapter php-http/message`).

**Comment by congnghiakhiem** [comment]
of course, I have installed the dependencies before. and they are in the vendor folder.

**Comment by mikemilano** [comment]
Ok, so now I remember. I was waiting for people to test it before I made an official release.

Can you let me know if this works?

`composer require foxrp/rippled-php:dev-master`

**Comment by mikemilano** [comment]
I decided to just create a release for version `1.0.0`. 

After you clear composer cache (`composer clearcache`), it should work as you were trying before: `composer install foxrp/rippled-php`

I encourage you to share your experience so I know if it's working well for developers.

**Comment by congnghiakhiem** [comment]
Thank you. I have installed successfully.

**Comment by feishaos** [comment]
php -v
PHP 7.2.7 (cli) (built: Jun 22 2018 06:27:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans




composer require foxrp/rippled-php:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - foxrp/rippled-php dev-master requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Installation request for foxrp/rippled-php dev-master -> satisfiable by foxrp/rippled-php[dev-master].
    - Installation request for php-http/httplug (locked at v2.0.0) -> satisfiable by php-http/httplug[v2.0.0].


Installation failed, reverting ./composer.json to its original content.
